### ISSUE TITLE
fails on cs101-selfservice

### ISSUE THREAD

**Issue by zendeavor** [dgorissen/coursera-dl#102]
https://class.coursera.org/cs101-selfservice/class 

```
[zendeavor@rancor mooc]$ coursera-dl cs101-selfservice
Coursera-dl v1.5.1 (html.parser)
Credentials found in .netrc file
Logging in as 'josh.s.mcgee@gmail.com'...

Course 1 of 1
* Collecting downloadable content from https://class.coursera.org/cs101-selfservice/lecture/index
* Got all downloadable content for cs101-selfservice
* cs101-selfservice will be downloaded to /home/zendeavor/mooc/cs101-selfservice
 - Downloading lecture/syllabus pages
Traceback (most recent call last):
  File "/usr/sbin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.5.1', 'console_scripts', 'coursera-dl')()
  File "/usr/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 578, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gzip_courses = args.gzip_courses)
  File "/usr/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 393, in download_course
    self.download_about(cname,course_dir)
  File "/usr/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 349, in download_about
    about_json = self.browser.open(about_url,timeout=self.TIMEOUT).read()
  File "/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 404: NOT FOUND
```

**Comment by dgorissen** [comment]
Sorry for the delay. Fixed in master.
