### ISSUE TITLE
Error downloading course

### ISSUE THREAD

**Issue by emumanu** [dgorissen/coursera-dl#109]
Hello,

I have tried to download this course mateymovimiento-001 and I got a 404 error:
- Collecting downloadable content from https://class.coursera.org/mateymovimiento-001/lecture/index
- Got all downloadable content for mateymovimiento-001
- mateymovimiento-001 will be downloaded to /openerp/descargas/rama6.1/coursera/nuevo_pip/mateymovimiento-001
  - Downloading lecture/syllabus pages
    Traceback (most recent call last):
    File "/usr/local/bin/coursera-dl", line 8, in <module>
    load_entry_point('coursera-dl==1.5.1', 'console_scripts', 'coursera-dl')()
    File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 578, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gzip_courses = args.gzip_courses)
    File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 393, in download_course
    self.download_about(cname,course_dir)
    File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 349, in download_about
    about_json = self.browser.open(about_url,timeout=self.TIMEOUT).read()
    File "/usr/local/lib/python2.6/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
    File "/usr/local/lib/python2.6/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
    mechanize._response.httperror_seek_wrapper: HTTP Error 404: NOT FOUND

**Comment by ghost** [comment]
This is not a bug of this program as this is not a valid url : https://www.coursera.org/course/mateymovimiento-001  _It returns a 404 not found_

But for example this is a valid url : https://www.coursera.org/course/db

**Comment by emumanu** [comment]
When you enter the course all material is under the mateymovimiento-001. The url that you point out for this course is https://www.coursera.org/course/precalculo

Anyway, neither mateymovimiento-001 nor precalculo works, so...

**Comment by xu-cheng** [comment]
It seems to be a fixed bug, fixed in 8a9f7a563e77fc1c1bb8d35b6f8c4aa8a11c54ee. Please try to use the latest version `coursera-dl`.

**Comment by emumanu** [comment]
Thank you xu-cheng. That worked.
