### ISSUE TITLE
Error downloading "Everything is the Same: Modeling Engineered Systems" (https://class.coursera.org/modelsystems-001/class)

### ISSUE THREAD

**Issue by bazazaba** [dgorissen/coursera-dl#113]
```
C:\WINDOWS\system32>c:\Python27\Scripts\coursera-dl.exe -u a#############h@gmail.com -p ####### -d Z:\Coursera\ modelsystems-001
Coursera-dl v1.5.1 (html.parser)
Maximum length of a path component set to 90
Logging in as 'a#############h@gmail.com'...

Course 1 of 1
* Collecting downloadable content from https://class.coursera.org/modelsystems-001/lecture/index
 Warning: failed to open the direct video link https://class.coursera.org/modelsystems-001/lecture/view?lecture_id=91: HTTP Error 404: Not Found
* Got all downloadable content for modelsystems-001
* modelsystems-001 will be downloaded to Z:\Coursera\modelsystems-001
 - Downloading lecture/syllabus pages
 - window.onload  function() (disappear).parent().parent().next().hide() (disappear).paren...
Traceback (most recent call last):
  File "c:\Python27\Scripts\coursera-dl-script.py", line 9, in <module> load_entry_point('coursera-dl==1.5.1', 'console_scripts', 'coursera-dl')()
  File "c:\Python27\lib\site-packages\courseradownloader\courseradownloader.py" line 578, in main d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gz ip_courses = args.gzip_courses)
  File "c:\Python27\lib\site-packages\courseradownloader\courseradownloader.py", line 421, in download_course os.makedirs(clsdir)
  File "c:\Python27\lib\os.py", line 157, in makedirs mkdir(name, mode) WindowsError: [Error 3] The system cannot find the path specified: 'Z:\\Coursera\\modelsystems-001\\01 - window.onload  function((disappear).parent().parent().next().hide() (disappear).paren...\\01 - SampleLecture1'

C:\WINDOWS\system32>
```

**Comment by dgorissen** [comment]
Can you confirm this happens with the current master branch?

---

Web    : http://dirkgorissen.com
Twitter : https://twitter.com/elazungu

**Comment by bazazaba** [comment]
Yes. It happens with the current master branch as well.

**Comment by dgorissen** [comment]
It worked for me but I made a small change. Update and please try again.
