### ISSUE TITLE
Invalid week filter, should be a comma separated list of integers                 

### ISSUE THREAD

**Issue by asampadeh** [dgorissen/coursera-dl#115]
Hi dg,

When I tried to run the coursera-dl found this error:

Traceback (most recent call last):
  File "C:\Python33\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==1.5.1', 'console_scripts', 'coursera-dl')()
  File "C:\Python33\lib\site-packages\setuptools-2.0.1-py3.3.egg\pkg_resources.py", line 352, in load_entry_point
  File "C:\Python33\lib\site-packages\setuptools-2.0.1-py3.3.egg\pkg_resources.py", line 2307, in load_entry_point
  File "C:\Python33\lib\site-packages\setuptools-2.0.1-py3.3.egg\pkg_resources.py", line 2021, in load
  File "C:\Python33\lib\site-packages\courseradownloader\courseradownloader.py", line 75
    print "Invalid week filter, should be a comma separated list of integers", e
                                                                            ^
SyntaxError: invalid syntax

**Comment by dgorissen** [comment]
Works here with python 2.7 but I made a small change. Try again with latest master and paste full log if you still have errors.

**Comment by side9show** [comment]
Hi,
Could you reopen this issue.  I am getting the same errors using python 3.3.  Any ideas?

Traceback (most recent call last):
  File "c:\Python33\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==1.5.1', 'console_scripts', 'coursera-dl')()
  File "C:\Python33\lib\site-packages\setuptools-0.9.6-py3.3.egg\pkg_resources.p
y", line 378, in load_entry_point
  File "C:\Python33\lib\site-packages\setuptools-0.9.6-py3.3.egg\pkg_resources.p
y", line 2566, in load_entry_point
  File "C:\Python33\lib\site-packages\setuptools-0.9.6-py3.3.egg\pkg_resources.p
y", line 2260, in load
  File "C:\Python33\lib\site-packages\courseradownloader\courseradownloader.py",
 line 75
    print "Invalid week filter, should be a comma separated list of integers", e
    ^
SyntaxError: invalid syntax

Thanks

**Comment by dgorissen** [comment]
It does not look like you are using the latest master version. Ensure you update first. (e.g., master uses print_("foo"), not print "foo"

**Comment by side9show** [comment]
I just installed it from pip.  And I tried doing an update through pip as well.  How else would I ensure it's the latest version?

**Comment by dgorissen** [comment]
Sorry, I should of clarified. Clone the git repo so you have the latest version as currently in git. The one in pip is the last released version.

**Comment by side9show** [comment]
Thanks for the clarification,

After doing that i received the following error:

Traceback (most recent call last):
  File "C:\Python33\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==1.5.1', 'console_scripts', 'coursera-dl')()
  File "C:\Python33\lib\site-packages\setuptools-0.9.6-py3.3.egg\pkg_resources.p
y", line 378, in load_entry_point
  File "C:\Python33\lib\site-packages\setuptools-0.9.6-py3.3.egg\pkg_resources.p
y", line 2566, in load_entry_point
  File "C:\Python33\lib\site-packages\setuptools-0.9.6-py3.3.egg\pkg_resources.p
y", line 2260, in load
  File "C:\Python33\lib\site-packages\coursera_dl-1.5.1-py3.3.egg\courseradownlo
ader\courseradownloader.py", line 1, in <module>
ImportError: No module named '_version'

Thanks again for the help.

**Comment by mganeshmohan** [comment]
Hi,  Has this been fixed for python 3.4.  I am using python 3.4 and getting the same error ImportError: No module named '_version'.  Or should I use only python 3.3 or 2.7?

Thanks

**Comment by dgorissen** [comment]
Please use python 2.7 for now. Its probably a small fix but I have little
or no bandwidth at the moment.

**Comment by mganeshmohan** [comment]
Thanks.  Will do and update.
