### ISSUE TITLE
File name too long Error

### ISSUE THREAD

**Issue by eyadsibai** [dgorissen/coursera-dl#122]
I am getting this error while trying to download one course

```
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.5.1', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 578, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gzip_courses = args.gzip_courses)
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 421, in download_course
    os.makedirs(clsdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)

OSError: [Errno 36] File name too long: '/home/user/courses/artificialvision-001/01 - Week 1 - Introduction to artificial vision with discrete graphical models/07 - 1.7 Examples of Discrete High-level vision (multi-object tracking with occlusion reasoning, 3D pose estimation from 2D images, image parsing using shape grammars towards large scale modeling and reconstruction) (13-45)'
```

**Comment by dgorissen** [comment]
try with the latest version from github and also see the -mppl argument

---

Dr. Dirk Gorissen
Research - Tech4Good - Flying Robots
Web     : http://dirkgorissen.com
Twitter  : https://twitter.com/elazungu
LinkedIn: http://www.linkedin.com/in/dirkgorissen

**Comment by eyadsibai** [comment]
Thanks ... it works now!
