### ISSUE TITLE
ImportError: cannot import name PY2

### ISSUE THREAD

**Issue by GildedHonour** [dgorissen/coursera-dl#129]
The error on Linux mint 16 while trying to run it:

```
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==2.0.1', 'console_scripts', 'coursera-dl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2309, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2015, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 18, in <module>
    from util import *
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/util.py", line 4, in <module>
    from six import print_, PY2
ImportError: cannot import name PY2
```

**Comment by dgorissen** [comment]
If I remember correctly you just need to upgrade six to a newer version

**Comment by GildedHonour** [comment]
Thanks.
