### ISSUE TITLE
ImportError: No module named '_version'

### ISSUE THREAD

**Issue by GildedHonour** [dgorissen/coursera-dl#140]
Arch linux:

```
Traceback (most recent call last):
  File "/usr/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==2.0.2', 'console_scripts', 'coursera-dl')()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python3.4/site-packages/courseradownloader/courseradownloader.py", line 1, in <module>
    import _version
ImportError: No module named '_version'
```

pip install version or pip install _version doesn't help.

**Comment by Forever-Young** [comment]
And how did you solve this?

**Comment by bhrgunatha** [comment]
It's a dupe: See previous report.
https://github.com/dgorissen/coursera-dl/issues/127
