### ISSUE TITLE
Fails on windows 7 x64

### ISSUE THREAD

**Issue by Jimbazuka** [dgorissen/coursera-dl#150]
D:\Python34>coursera-dl -h
Traceback (most recent call last):
  File "D:\Python34\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==3.0.0', 'console_scripts', 'coursera-dl')()
  File "D:\Python34\lib\site-packages\pkg_resources.py", line 353, in load_entry
_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\Python34\lib\site-packages\pkg_resources.py", line 2302, in load_entr
y_point
    return ep.load()
  File "D:\Python34\lib\site-packages\pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['**name**'])
  File "D:\Python34\lib\site-packages\courseradownloader\courseradownloader.py",
 line 76
    print "Invalid week filter, should be a comma separated list of integers", e

```
                                                                        ^
```

SyntaxError: invalid syntax

D:\Python34>

**Comment by Jimbazuka** [comment]
This only happens in Python 3.4.1 but does not happen on Python 2.7
