### ISSUE TITLE
io.UnsupportedOperation: seek

### ISSUE THREAD

**Issue by 1xch** [dgorissen/coursera-dl#163]
```
Starting new HTTPS connection (1): d28rh4a8wq0iu5.cloudfront.net
Traceback (most recent call last):
File "./coursera-dl", line 6, in <module>
coursera_dl.main()
File "/coursera_dl.py", line 781, in main
if download_class(args, class_name):
File "/coursera_dl.py", line 761, in download_class
args.intact_fnames)
File "/coursera_dl.py", line 400, in download_lectures
downloader.download(url, lecfn)
File "/downloaders.py", line 43, in download
self._start_download(url, filename)
File "/downloaders.py", line 309, in _start_download
progress.report(r.raw.tell())
io.UnsupportedOperation: seek
```

**Comment by magbak** [comment]
Using the --curl option allowed me to bypass this issue.
