### ISSUE TITLE
Unknown class

### ISSUE THREAD

**Issue by marcofat** [dgorissen/coursera-dl#179]
Hello, I downloaded without any problem the “Algorithms: Design and Analysis, Part 1″ course using the command line:
“coursera-dl -u myusername -p mypassword -d /my/coursera/courses/ algo-2012-001″

Now I’m trying to download the “competitive strategy” course material (https://www.coursera.org/learn/competitivestrategy) and I would like to ask you a piece of advice in choosing the right course name from the url to put into the command line.

If I use “coursera-dl -u myusername -p mypassword -d /my/coursera/courses/ competitivestrategy” I get the following:
“Exception: Unknown class competitivestrategy”

If I use “coursera-dl -u myusername -p mypassword -d /my/coursera/courses/ learn/competitivestrategy” I get the following:
“Exception: Failed to find csrf cookie”

Thank you for your help and the great script!

**Comment by mishari** [comment]
I am having the same issue, the class https://www.coursera.org/learn/competitivestrategy seems to have a new page format with no download button.

```
Traceback (most recent call last):
  File "/my_env/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "/my_env/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 654, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gzip_courses = args.gzip_courses)
  File "/my_env/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 418, in download_course
    self.browser.open(self.AUTH_URL % cname,timeout=self.TIMEOUT)
  File "/my_env/lib/python2.7/site-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/my_env/lib/python2.7/site-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found
```

**Comment by mishari** [comment]
I just realized this is a duplicate of  #151
