### ISSUE TITLE
It doesn't work recently!

### ISSUE THREAD

**Issue by javadr** [dgorissen/coursera-dl#18]
Dear Dirk,
Hi
At first lots of thanks for making such a nice course downloader, Secondly it doesn't work for my recently. 
I used it few days ago but after updating my OS(Fedora 18) it doesn't work, e.g. when I wanted to download the scientificcomp-002 course I got the below error:
- Collecting downloadable content from http://class.coursera.org/scientificcomp-002/lecture/index
  Traceback (most recent call last):
  File "/usr/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.2.1', 'console_scripts', 'coursera-dl')()
  File "/usr/lib/python2.7/site-packages/coursera_dl-1.2.1-py2.7.egg/courseradownloader/courseradownloader.py", line 472, in main
    d.download_course(cn,dest_dir=args.dest_dir)
  File "/usr/lib/python2.7/site-packages/coursera_dl-1.2.1-py2.7.egg/courseradownloader/courseradownloader.py", line 194, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/usr/lib/python2.7/site-packages/coursera_dl-1.2.1-py2.7.egg/courseradownloader/courseradownloader.py", line 112, in get_downloadable_content
    hrefs = classResources.findAll('a')
  AttributeError: 'NoneType' object has no attribute 'findAll'

or as another example by downloading neuralnets-2012-001 course it produces: 
- Collecting downloadable content from http://class.coursera.org/neuralnets-2012-001/lecture/index
  Traceback (most recent call last):
  File "/usr/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.2.1', 'console_scripts', 'coursera-dl')()
  File "/usr/lib/python2.7/site-packages/coursera_dl-1.2.1-py2.7.egg/courseradownloader/courseradownloader.py", line 472, in main
    d.download_course(cn,dest_dir=args.dest_dir)
  File "/usr/lib/python2.7/site-packages/coursera_dl-1.2.1-py2.7.egg/courseradownloader/courseradownloader.py", line 194, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/usr/lib/python2.7/site-packages/coursera_dl-1.2.1-py2.7.egg/courseradownloader/courseradownloader.py", line 116, in get_downloadable_content
    resourceLinks = [ (h['href'],None) for h in hrefs]
  File "/usr/lib/python2.7/site-packages/beautifulsoup4-4.1.3-py2.7.egg/bs4/element.py", line 879, in **getitem**
    return self.attrs[key]

Could you help me with this?
Best

**Comment by dgorissen** [comment]
A quick test here shows it all works. Ensure you have the latest version. Did you accept the honour code for the class? You must do so manually on the site first.

**Comment by javadr** [comment]
I don't know why it didn't work by these days while I downloaded some courses before that! 
Today,  I tested again and it works now. :+1: 
So thanks again for your nice effort.
