### ISSUE TITLE
spynner.browser.SpynnerTimeout: SPYNNER waitload: Timeout reached: 5 retries for 2s delay

### ISSUE THREAD

**Issue by emumanu** [dgorissen/coursera-dl#30]
Hi,

I've tried the new version. I had to install libxml2-dev, libxslt1-dev and pyqt4-dev-tools to make coursera-dl to work. However now after running it I've got:

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 8, in <module>
    load_entry_point('coursera-dl==1.3', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 481, in main
    d.login()
  File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 78, in login
    page = wait_for_content(lambda s: s.find(id="signin-password"))
  File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 72, in wait_for_content
    webkit.wait_for_content(can_continue, 5, "Timout reached, please check your network and username/password", delay=2)
  File "/usr/local/lib/python2.6/dist-packages/spynner/browser.py", line 868, in wait_for_content
    raise SpynnerTimeout(msg)
spynner.browser.SpynnerTimeout: SPYNNER waitload: Timeout reached: 5 retries for 2s delay.
Timout reached, please check your network and username/password

Please help

**Comment by dgorissen** [comment]
This is probably an authentication issue. Anyways, turned out the pyqt stuff was overkill, I removed those dependencies again and uploaded a new version. Please upgrade and try again. Reopen if any issues.

**Comment by jhg** [comment]
I have timeout reached but in page that not use authentication. I one all but in other only without window, with window load good.

**Comment by dgorissen** [comment]
If this is with coursera-dl ignore and simply use the latest version.
