### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by dniku** [dgorissen/coursera-dl#31]
Windows 7 32-bit, Python 2.7.2

```
D:\> pip install coursera-dl
Downloading/unpacking coursera-dl
  Running setup.py egg_info for package coursera-dl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "D:\build\coursera-dl\setup.py", line 5, in <module>
        import version
    ImportError: No module named version
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "D:\build\coursera-dl\setup.py", line 5, in <module>

    import version

ImportError: No module named version
```

**Comment by dgorissen** [comment]
Thanks, should be fixed now.

**Comment by TashiDundrup** [comment]
Hi I have a similar issue, even after upgrading with pip just now.

Windows Vista 64 bit,  Python 2.7.2

I receive this error:
"
C:\Users\A>coursera-dl -u XXXX -p XXX statics1-001
Traceback (most recent call last):
  File "C:\Python27\scripts\coursera-dl-script.py", line 8, in <module>
    load_entry_point('coursera-dl==1.4.5', 'console_scripts', 'coursera-dl')()
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py",
 line 486, in main
    print "Coursera-dl v%s (%s)" % (version.VERSION,parser)
AttributeError: 'module' object has no attribute 'VERSION'

"

**Comment by dgorissen** [comment]
This should not happen with the latest version. I just tested it on a clean windows machine and it installs properly. To be sure first remove the package and then pip install it again.
