### ISSUE TITLE
Failed to find csrf cookie

### ISSUE THREAD

**Issue by kseistrup** [dgorissen/coursera-dl#35]
This is the very first time I ran coursera-dl:

``` pytb
$ coursera-dl -u myUsername -p myPassword 'Think Again'
Coursera-dl v1.4.5 (lxml)
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.4.5', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 497, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 71, in login
    if not csrfcookie: raise Exception("Failed to find csrf cookie")
Exception: Failed to find csrf cookie
```

Python 2.7 on Linux 3.2.

**Comment by dgorissen** [comment]
You should use the course name as found in the url, examples are posa-001, ml-2012-01, etc. Think again has not started yet it seems so you will not be able to download it until it does.

**Comment by kseistrup** [comment]
Ah, thanks — and sorry for not understanding what was meant by “course name as found in the url” when I attempted to download…

This indeed helps.  I was enrolled in the Think Again 2012, but I wish to download the videos.  Downloads are rolling now.  :)

**Comment by tdhopper** [comment]
I'm getting this for mmds-001 which started today and has video available.

**Comment by pshvechikov** [comment]
It seems, that there is new naming convention of a csrf cookie.
I constantly get en error 

```
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 649, in main
    d.login(args.course_names[0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 141, in login
    if not csrfcookie: raise Exception("Failed to find csrf cookie")
Exception: Failed to find csrf cookie
```

Here it is what i get if i print `cj` before https://github.com/dgorissen/coursera-dl/blob/f2a9c1e74011b3b6a7c832e7a6717daff416f0c1/courseradownloader/courseradownloader.py#L139  (of courser values are somewhay altered by myself because of privacy reasons). 

```
[Cookie(version=0, name='CSRF3-Token', value='1fL', port=None, port_specified=False, domain='.coursera.org', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=16, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='__204u', value='', port=None, port_specified=False, domain='.coursera.org', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=1466, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False)]
```

So in my case the line 

```
csrfcookie = [c for c in cj if c.name == "csrf_token"]
```

always fails.

I think it should be 

```
csrfcookie = [c for c in cj if c.name.lower() == "csrf3-token"]
```

Am i wrong ?

**Comment by pshvechikov** [comment]
This change to 139 line in `courseradownloader.py` fixed this issue for me. Now i am struggling with the message 

```
Warning: no downloadable content found for learn/learning-how-to-learn, did you accept the honour code?
```

And i have no idea what to do with this.
