### ISSUE TITLE
No ''load_page" object

### ISSUE THREAD

**Issue by rom85** [dgorissen/coursera-dl#37]
Hello. I have the following error:

C:\Portable Python 2.7.3.1\App\Scripts>coursera-dl -u rom85@email.ua -p mypass -d d:\coursera\ comnetworks-2012-001
Coursera-dl v1.4.5 (lxml)

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/comnetworks-2012-001/lecture/index
  Traceback (most recent call last):
  
  File "C:\Portable Python 2.7.3.1\App\Scripts\coursera-dl-script.py", line 8, in <module> load_entry_point('coursera-dl==1.4.5', 'console_scripts', 'coursera-dl')()
  
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 503, in main parser = argparse.ArgumentParser(description='Download Coursera.org course videos/docs for offline use.')
  
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 257, in download_course
  
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 176, in get_downloadable_content

AttributeError: 'CourseraDownloader' object has no attribute 'load_page'

And download doesn't go. Please, tell me what is wrong. Thank you.

**Comment by dgorissen** [comment]
Well spotted, should be fixed now. Upgrade and please report back any more problems if they occur.

**Comment by rom85** [comment]
Yes, thank you. It works fine now.
