### ISSUE TITLE
retrieval of files is stuck when connection is lost

### ISSUE THREAD

**Issue by shtratos** [dgorissen/coursera-dl#39]
Hi

I've tried to download several courses at once and when my network connection was lost - coursera-dl got stuck for hours.

I would've expected it to exit on timeout.

I did Ctrl+C and here's the trace:

<pre>
Course 3 of 4
* Collecting downloadable content from https://class.coursera.org/bluebrain-001/lecture/index
* Got all downloadable content for bluebrain-001
* bluebrain-001 will be downloaded to /Users/irulan/education/Coursera/bluebrain-001
 - Downloading lecture/syllabus pages
 - Lesson 1 - Brain excitements for the 21st century
  - Downloading resources for Welcome words and great thinkers (09-31)
  - Downloading resources for The blossoming of the brain in the world (07-53)
  - Downloading resources for The connectomics (10-31)
  - Downloading resources for Brainbow (08-06)
  - Downloading resources for Brain Machine Interface (BMI) (16-48)
  - Downloading resources for Optogenetics (07-24)
  - Downloading resources for Simulation of the brain - Blue Brain Project (08-57)
 - Lesson 2 - The materialistic mind  your brains ingredients
  - Downloading resources for The Neuron (09-19)
  - Downloading resources for The Neuron Doctrine (09-11)
  - Downloading resources for The Neuron as IO Device part 1 (08-04)
  - Downloading resources for The Axon (14-10)
  - Downloading resources for The Dendrite (08-34)
  - Downloading resources for Neuron Types (11-08)
  - Downloading resources for The Synapse (14-07)
  - Downloading resources for The Neuron as IO Device part 2 (07-27)
 - Lesson 3 - Electrifying brains passive electrical signals
  - Downloading resources for Sources for Lecture 3 - No Video
    - failed:  http://en.wikipedia.org/wiki/Ohm%27s_law HTTP Error 403: Forbidden
    - failed:  http://en.wikipedia.org/wiki/Kirchhoff%27s_circuit_laws HTTP Error 403: Forbidden
    - failed:  http://en.wikipedia.org/wiki/RC_circuit HTTP Error 403: Forbidden
    - failed:  https://class.coursera.org/bluebrain-001/lecture/download.mp4?lecture_id=39 HTTP Error 500: Internal Server Error
  - Downloading resources for The Cell as RC Circuit (11-01)
  - Downloading resources for The Voltage Equation for the Passive Cell (09-20)
  - Downloading resources for The Membrane Time Constant (14-03)
  - Downloading resources for Temporal Summation (09-31)
  - Downloading resources for The Resting Potential (08-54)
  - Downloading resources for The Synaptic Potential Part 1 (09-38)
  - Downloading resources for The Synaptic Conductance (06-19)
^CTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/coursera-dl", line 8, in <module>
    load_entry_point('coursera-dl==1.4.7', 'console_scripts', 'coursera-dl')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 546, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 372, in download_course
    self.download(classResource,target_dir=clsdir,target_fname=tfname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 282, in download
    self.browser.retrieve(url,filepath)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_opener.py", line 277, in retrieve
    block = fp.read(bs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mechanize/_response.py", line 195, in read
    data = self.wrapped.read(to_read)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 561, in read
    s = self.fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
</pre>

**Comment by dgorissen** [comment]
The downloads itself are handled by mechanize, I have added an explicit timeout, should help.

**Comment by shtratos** [comment]
cool, thanks
