### ISSUE TITLE
NameError: global name 'p' is not defined

### ISSUE THREAD

**Issue by pr-ravi** [dgorissen/coursera-dl#43]
I have the following error.. 
Don't know much python.. but here is the message...
I have gotten the message for 3 courses...

Coursera-dl v1.4.7 (lxml)

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/hwswinterface-001/lecture/index
  Traceback (most recent call last):  
  File "/usr/local/bin/coursera-dl", line 9, in <module>  
    load_entry_point('coursera-dl==1.4.7', 'console_scripts', 'coursera-dl')()  
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 546, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)  
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 296, in download_course  
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)  
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 208, in get_downloadable_content  
    bb = BeautifulSoup(p,self.parser)  
  NameError: global name 'p' is not defined

**Comment by dgorissen** [comment]
Was a silly typo, should be fixed now. Thanks for reporting.
