### ISSUE TITLE
KeyError:'href' for course einstein-001

### ISSUE THREAD

**Issue by indraastra** [dgorissen/coursera-dl#44]
Hi, I'm seeing the following error:

``` python
Course 1 of 5
* Collecting downloadable content from https://class.coursera.org/einstein-001/lecture/index
Traceback (most recent call last):
  File "C:\Python27\Scripts\coursera-dl-script.py", line 8, in <module>
    load_entry_point('coursera-dl==1.4.8', 'console_scripts', 'coursera-dl')()
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 59
8, in main
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 30
1, in download_course
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 19
4, in get_downloadable_content
  File "C:\Python27\lib\site-packages\bs4\element.py", line 879, in __getitem__
    return self.attrs[key]
KeyError: 'href'
```

**Comment by rodch-us** [comment]
I have successfully downloaded the contents in this course without any errors. This error maybe due to something at your end, make sure you have accepted honor code before downloading.

**Comment by indraastra** [comment]
Odd, but very likely. I've downloaded it in the past successfully as well but haven't been able to recently because of that error. Did you mean you downloaded this just before you posted your comment?

I'm running python 2.7.3 from a Windows 7 command prompt.

**Comment by dgorissen** [comment]
Sorry for the delay in looking at this. Can you just confirm that this problem still occurs with the latest git checkout. If so does switching parsers (e.g., using html5lib instead of lxml) solve the issue? (see the -q option)
