### ISSUE TITLE
Crash during download & skipped videoes

### ISSUE THREAD

**Issue by AllanLRH** [dgorissen/coursera-dl#47]
Just got this error:

```
* Collecting downloadable content from https://class.coursera.org/posa-001/lecture/index
Traceback (most recent call last):
  File "/Users/allan/Dropbox/Crap/inst/coursera-dl/courseradownloader/courseradownloader.py", line 545, in <module>
    main()
  File "/Users/allan/Dropbox/Crap/inst/coursera-dl/courseradownloader/courseradownloader.py", line 542, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "/Users/allan/Dropbox/Crap/inst/coursera-dl/courseradownloader/courseradownloader.py", line 295, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/Users/allan/Dropbox/Crap/inst/coursera-dl/courseradownloader/courseradownloader.py", line 207, in get_downloadable_content
    bb = BeautifulSoup(p,self.parser)
NameError: global name 'p' is not defined
```

The error seem specific to this course (Pattern-Oriented Software Architectures for Concurrent and Networked Software), as two other did not crash.

I think all course material is available, judging from the course dashboard: 
![image](http://www.fys.ku.dk/~bzg778/longTermStorage/courserScreenDump1.png)

Also, for some reason, not all the available material was downloaded from the course datasci-001 (Introduction to Data Science). The script just went on to the next, guitar-001, (Introduction to Guitar), where one video were skipped.

Albeit I have no real knowledge about how this script works, I have an idea that the problem is fetching the downloadable content, as several videos were downloaded without problems.

**Comment by AllanLRH** [comment]
Newer mind. Hadn't updated to the newest version (I'm a git noob) as I thought I did. Works now :flushed:
