### ISSUE TITLE
Problem downloading

### ISSUE THREAD

**Issue by danzean** [dgorissen/coursera-dl#48]
Hi,

I've had no problems using the downloader until today when I got the following error message:

Warning: lxml not available, falling back to built-in 'html.parser' (see -q option), this may cause problems on Python < 2.7.3
HTML parser set to html.parser
- Collecting downloadable content from https://class.coursera.org/humanphysio-001/lecture/index
  Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 8, in <module>
    load_entry_point('coursera-dl==1.4.1', 'console_scripts', 'coursera-dl')()
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 495, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 256, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 175, in get_downloadable_content
    bb = self.load_page(lurl)
  AttributeError: 'CourseraDownloader' object has no attribute 'load_page'

**Comment by cm325** [comment]
I got this:

Warning: lxml not available, falling back to built-in 'html.parser' (see -q option), this may cause problems on Python < 2.7.3
Coursera-dl v1.4.8 (html.parser)

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/genes-001/lecture/index
  Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 8, in <module>
    load_entry_point('coursera-dl==1.4.8', 'console_scripts', 'coursera-dl')()
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 598, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 301, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 212, in get_downloadable_content
    pg = self.browser.open(lurl,timeout=self.TIMEOUT)
  File "/Library/Python/2.7/site-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/Library/Python/2.7/site-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
  mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

**Comment by cm325** [comment]
I installed lxml, but the issue was the same, the problem is specific to this course, other courses are downloading just fine-

**Comment by dgorissen** [comment]
I also get the problem by @cm325, this is because genes-001 has a lecture with no associated video. Should no longer crash now.

**Comment by andremrsantos** [comment]
I just upgrade my script with '''pip install coursera-dl upgrade''' and still raises the same issue regarding the gene-001 course. How can I fix it?

**Comment by dgorissen** [comment]
I dont know the gene-001 course and the humanphysio one does not start
until august. Could you give the full gene-001 url so I can signup and
test. I did a quick search but it was not immediately obvious which one it
was.

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by dgorissen** [comment]
just realized this was fixed already but just not released (my previous reply was via email). I just released a new version and it should work there.
