### ISSUE TITLE
Cannot download course due to AttributeError

### ISSUE THREAD

**Issue by kurthuwig** [dgorissen/coursera-dl#58]
<pre>
Coursera-dl v1.4.8 (lxml)
Logging in as 'coursera.kurt@huwig.de'...

Course 1 of 1
* Collecting downloadable content from https://class.coursera.org/datasci-001/lecture/index
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.4.8', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 598, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 301, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 186, in get_downloadable_content
    hrefs = classResources.findAll('a')
AttributeError: 'NoneType' object has no attribute 'findAll'
</pre>

**Comment by dgorissen** [comment]
This works for me. Ensure you are using the latest version and also try an alternative parser (e.g., html.parser).

**Comment by kurthuwig** [comment]
Thank you, the option "-p html.parser" did the trick. Is there a reason that it is not the default?

**Comment by hknust** [comment]
Thanks, I had the same issue. The option is **-q** html.parser, though.

**Comment by dgorissen** [comment]
html.parser now the default.
