### ISSUE TITLE
Issue when downloading course  https://class.coursera.org/writing2-001/lecture/index

### ISSUE THREAD

**Issue by mlteppi** [dgorissen/coursera-dl#61]
Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/writing2-001/l
  ecture/index
  Traceback (most recent call last):
  File "C:\Python27\Scripts\coursera-dl-script.py", line 8, in <module>
    load_entry_point('coursera-dl==1.4.8', 'console_scripts', 'coursera-dl')()
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 60
  7, in main
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 31
  0, in download_course
  File "build\bdist.win32\egg\courseradownloader\courseradownloader.py", line 17
  2, in get_downloadable_content
  AttributeError: 'NoneType' object has no attribute 'text'

**Comment by AllanLRH** [comment]
Had a similar error. Calling coursera-dl with the argument `-q 'html.parser'` fixed it.

**Comment by dgorissen** [comment]
html.parser is now the default
