### ISSUE TITLE
No module named html.entities

### ISSUE THREAD

**Issue by TashiDundrup** [dgorissen/coursera-dl#7]
Dear Dirk,

Thanks for writing this module. I have the following error arise, even though pip install says my beautifulsoup4 is up to date: 

"Traceback (most recent call last):
  File "D:\Documents\Desktop\Coursera\coursera-dl.py", line 9, in <module>
    from bs4 import BeautifulSoup
  File "C:\Python27\lib\site-packages\bs4__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "C:\Python27\lib\site-packages\bs4\builder__init__.py", line 4, in <module>
    from bs4.element import (
  File "C:\Python27\lib\site-packages\bs4\element.py", line 5, in <module>
    from bs4.dammit import EntitySubstitution
  File "C:\Python27\lib\site-packages\bs4\dammit.py", line 11, in <module>
    from html.entities import codepoint2name
ImportError: No module named html.entities"

On Windows vista

What do you recommend?

**Comment by dgorissen** [comment]
The only thing I can think of is this: http://www.crummy.com/software/BeautifulSoup/bs4/doc/#problems-after-installation

Can you double check that your only python installation is 2.7. Sames goes for your pip installation.
