### ISSUE TITLE
Download archived lectures

### ISSUE THREAD

**Issue by casperc** [dgorissen/coursera-dl#94]
It would be great if it was possible to download archived lectures, but currently it fails with: 

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.4.11', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 663, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 85, in login
    if not csrfcookie: raise Exception("Failed to find csrf cookie")
Exception: Failed to find csrf cookie

**Comment by dgorissen** [comment]
As far as I am aware this is not possible.

**Comment by mahiinside** [comment]
I am also getting the same error , can any one please help me
