### ISSUE TITLE
[Errno 10013] An attempt was made to access a s ocket in a way forbidden by its access permissions>

### ISSUE THREAD

**Issue by liangteh** [dgorissen/coursera-dl#95]
Hi, 

I encountered the following errors while downloading the videos.

Traceback (most recent call last):
  File "C:\Python27\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==1.5', 'console_scripts', 'coursera-dl')()
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py",
 line 558, in main
    d.login(args.course_names[0])
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py",
 line 94, in login
    res = opener.open(req)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10013] An attempt was made to access a s
ocket in a way forbidden by its access permissions>

**Comment by dgorissen** [comment]
Mmm, never seen that before. What OS / Python version? Please also paste the full log. Are you sure you are not running as a user (or in a directory) with particular privilege restrictions?
